[project]
name = "rl-environments"
version = "0.1.0"
description = "Training-Ready RL Environments + Evals"
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = [
    "dotenv>=0.9.9",
    "verifiers>=0.1.2.post0",
]
authors = [
    { name="Lucien Thomas", email="lucienthomas00@gmail.com" },
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "pre-commit>=4.2.0",
    "ruff>=0.12.1",
]


[tool.ruff.lint]
select = ["F", "I"]
ignore = ["F722", "F821"] # Need to ignore for jaxtyping (https://docs.kidger.site/jaxtyping/faq/)

[tool.ruff]
line-length = 120
